server:
    tomcat:
        max-threads: 3000
        min-spare-threads: 10
    port: 3040
eureka:
  client:
    service-url:
        defaultZone: http://10.111.0.151:8761/eureka/,http://10.111.0.152:8761/eureka/
    should-unregister-on-shutdown: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
spring:
  application:
    name: user-api
  datasource: #以下数据库部分自行修改
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://host:port/dbname?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: username
      password: password
      dbcp2:
         max-idle: 10
         max-wait-millis: 10000
         min-idle: 5
         initial-size: 5
         validation-query: select 1
         test-on-borrow: false
         test-while-idle: true
         time-between-eviction-runs-millis: 18800
  transaction:
      rollback-on-commit-failure: true
  redis: #以下redis部分自行修改
       host: host
       port: 6379
       password: password
       lettuce:
         pool:
           min-idle: 4
           max-active: 8
       database: 10
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 10Mb
mybatis:
    mapperLocations: classpath:mapper/**/*.xml